const names={home:"Overview",models:"Models",playground:"Playground",training:"Training",deployments:"Deployments",datasets:"Datasets",usage:"Usage & limits","api-keys":"API keys",settings:"Settings"};
const key="forge.demo.v1",seed={models:["Llama 3.1 8B Instruct","Mistral Nemo 12B","Customer Support v2","Code Assistant"],jobs:["Customer Support v2 · Training","Product FAQ adapter · Completed"],deployments:["llama-support-prod","code-assistant-dev"]};
let data;try{data={...seed,...JSON.parse(localStorage.getItem(key)||"{}")}}catch{data={...seed}};
let page=location.hash.slice(1)||"home";
const save=()=>localStorage.setItem(key,JSON.stringify(data)), esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function render(){if(!names[page])page="home";document.querySelector("#breadcrumb-current").textContent=names[page];document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));document.querySelector("#model-count").textContent=data.models.length;let body={home:`<div class="eyebrow">WORKSPACE OVERVIEW</div><h1>Your AI workspace</h1><p>Build, train, and run models on your terms.</p><div class="banner"><small>YOUR PRIVATE AI STUDIO</small><h2>Good things are taking shape.</h2><p>Models, training runs, and endpoints in one place.</p><button data-page="models">Explore models →</button></div><div class="cards"><article><small>Active models</small><h2>${data.models.length}</h2></article><article><small>Training jobs</small><h2>${data.jobs.length}</h2></article><article><small>API requests</small><h2>16,044</h2></article><article><small>Total tokens</small><h2>2.4M</h2></article></div><section class="panel"><h2>Recent models</h2>${data.models.map(x=>`<p>⬡ &nbsp;${esc(x)} <span class="tag">Ready</span></p>`).join("")}</section><p class="note">Preview data only. Connect your own hardware and model runtime for real training and inference.</p>`,
models:`<div class="eyebrow">MODEL LIBRARY</div><h1>Models</h1><p>Your imported, fine-tuned, and ready-to-deploy models.</p><button data-action="add-model">＋ Import model</button><section class="panel">${data.models.map(x=>`<p>⬡ &nbsp;${esc(x)} <span class="tag">Local record</span></p>`).join("")}</section>`,
playground:`<div class="eyebrow">TEST & ITERATE</div><h1>Playground</h1><p>Simulated responses · local preview</p><section class="panel"><div id="chat">${(data.chat||[]).map(x=>`<p><b>${x.role}:</b> ${esc(x.text)}</p>`).join("")||"Connect a runtime for real model responses."}</div><form id="chat-form"><input id="chat-input" placeholder="Message your model…" required><button>Send</button></form><p class="note">This preview does not connect to an LLM.</p></section>`,
training:`<div class="eyebrow">MODEL DEVELOPMENT</div><h1>Training</h1><p>Fine-tune open models on data you control.</p><div class="notice">A GPU runtime, base model access, and prepared data are required. No training happens in this preview.</div><section class="panel">${data.jobs.map(x=>`<p>${esc(x)}</p>`).join("")}</section>`,
deployments:`<div class="eyebrow">MODEL SERVING</div><h1>Deployments</h1><p>Serve models through APIs on infrastructure you control.</p><div class="notice">These sample records do not serve model responses.</div><section class="panel">${data.deployments.map(x=>`<p>${esc(x)} <span class="tag">Sample</span></p>`).join("")}</section>`,
datasets:`<div class="eyebrow">YOUR DATA</div><h1>Datasets</h1><p>Manage training and evaluation data.</p><section class="panel">No datasets yet. Dataset storage is not connected.</section>`,
usage:`<div class="eyebrow">ACCOUNT</div><h1>Usage & limits</h1><p>Resources available in this workspace.</p><section class="panel">Local demo · no cloud quota enabled.<p>Hosting still needs hardware, electricity, storage, and internet access. We cannot promise lifetime free compute.</p></section>`,
"api-keys":`<div class="eyebrow">DEVELOPER TOOLS</div><h1>API keys</h1><section class="panel">Demo-only keys. They do not authenticate requests.</section>`,
settings:`<div class="eyebrow">PREFERENCES</div><h1>Settings</h1><section class="panel">Preferences are saved in this browser profile.<p><button data-action="reset">Reset demo data</button></p></section>`};
document.querySelector("#page-container").innerHTML=body[page];document.querySelector("#page-container").querySelectorAll("[data-page]").forEach(x=>x.onclick=()=>go(x.dataset.page));const f=document.querySelector("#chat-form");if(f)f.onsubmit=e=>{e.preventDefault();data.chat=data.chat||[];data.chat.push({role:"You",text:document.querySelector("#chat-input").value},{role:"Forge preview",text:"Connect a model runtime for a real answer."});save();render()}}
function go(p){page=p;location.hash=p;render();document.querySelector("#sidebar").classList.remove("open")}
document.body.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p){e.preventDefault();go(p.dataset.page)}const a=e.target.closest("[data-action]")?.dataset.action;if(a==="runtime"||a==="help")alert("Forge is a self-hosted model workspace preview. Connect an inference backend and hardware to use real models.");if(a==="add-model"){const n=prompt("Model name");if(n){data.models.unshift(n);save();render()}}if(a==="reset"){data={...seed};save();render()}});
document.querySelector("#mobile-menu").onclick=()=>document.querySelector("#sidebar").classList.toggle("open");window.addEventListener("hashchange",()=>{page=location.hash.slice(1)||"home";render()});
const toggle=document.querySelector("#theme-toggle");function theme(t){document.documentElement.dataset.theme=t;toggle.textContent=t==="dark"?"☀":"☾";toggle.setAttribute("aria-label",t==="dark"?"Switch to light theme":"Switch to dark theme");document.querySelector('meta[name="theme-color"]').content=t==="dark"?"#111513":"#f7f8fa"}theme(localStorage.getItem("forge.theme")||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light"));toggle.onclick=()=>{const t=document.documentElement.dataset.theme==="dark"?"light":"dark";localStorage.setItem("forge.theme",t);theme(t)};render();
